name: apk_resep_makanan
description: A new Flutter project.

publish_to: "none" # Prevent publishing to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.0.3
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
